### ISSUE TITLE
detector.js:751 cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by AlexNovicov** [blackmirror1980/detector-js#15]
I am get an error - https://i.imgur.com/sHm6y0D.png

**Comment by ghost** [comment]
this should be fixed. sorry for late answer.... anyhow you should check if something else is overriding the toLowerCase native method of js strings.

as i see from that screenshot, there's something overriding the toString method of functions....

can u check this?

**Comment by ghost** [comment]
the whole stack is not regarding methods of detector
it happens on a keyDown event of something

![sHm6y0D](https://user-images.githubusercontent.com/1705111/109818907-cc6ffe00-7c33-11eb-91a7-462a9023f5af.png)

i mean, i don't even get why detector.js code is doing something on handleKeyDown event handler.... and is also running in an "eval" method call.... eval is evil.

May i help in some way?

**Comment by AlexNovicov** [comment]
Sorry, but this question was quite a long time ago and I don't remember where it came from

**Comment by ghost** [comment]
You're right.

Anyhow... i'm sorry for my late answer!
